export const funFacts = [
    `Due to their low-calorie diet, red pandas do little more than eat and sleep`,
    `The scientific name for the red panda is Ailurus fulgens, which means "red shining cat"`,
    `The red panda is found in five countries: Nepal, India, Bhutan, Myanmar, and China`,
    `A panda year is equivalent to three human years`,
    `Pandas will abandon a child if she has twins`,
    `Pandas like climbing trees and can swim.`,
    `A panda can poop 28 kilos (62 lb) per day!`,
    `Approximately 400,000 people are bitten by cats in the U.S. annually`,
    `A cat can jump up to five times its own height in a single bound`,
    `On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life`,
    `Approximately 1/3 of cat owners think their pets are able to read their minds`,
    `Cats spend nearly 1/3 of their waking hours cleaning themselves`,
    `A cat’s heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute`,
    `There are over 20 species of fox`,
    `On cold nights, foxes cover themselves with their tail, like a blanket, to keep warm`,
    `Red foxes have over 20 different calls that they can make and understand`,
    `"Vixen" is the name for a female fox, while male foxes are called "tods" or "dog foxes,"`,
    `The only continents that don't have red foxes are South America and Antarctica`,
    `Arctic foxes can live and hunt on both frozen land and sea ice`,
    `Arctic foxes are able to slow down their own heart rate, allowing them to quasi-hibernate for up to two weeks`,
    `Desert foxes have bodies that are only between 9 and 16 inches (22 to 40 cm) long`,
    `Although very small, desert foxes can jump two feet in the air and can leap across distances of four feet`
]